[[redirects]]
  from = "/proxy/*"
  to = "https://stdict.korean.go.kr/:splat"
  status = 200
  force = true

[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
